name: captronnc
favicon: null
layout_spectrum: 0.2745147447567433
typography_spectrum: 0.25408077193424106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7725089539308101
  lightness: 0.08602102333679795
  saturation: 0.9454567760694772
  rhythmicContrast: 0.22870458662509918
purpose: []
